### ISSUE TITLE
How to trigger the lambda?

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline-sitemap#4]
The lambda must be triggered by an event which will depend on the frequency we want to update the sitemap. Once a week? At each new item inserted in elasticsearch (might cost a lot if new items are added often)?

Another solution might be to trigger the lambda manually, easy to implement but maybe not very effecient and time consuming for @jamieu.

@jamieu do you have an idea on long we want to wait before triggering the lambda? Or is there a specific event we can monitor which will triger the lambda?

@Danwhy @nelsonic do you have any more specific ideas on this?

**Comment by jamieu** [comment]
I was thinking daily (but weekly would suffice one the site has
settled down post launch and the inivitable post launch record changes).

**Comment by SimonLab** [comment]
@alanshaw confirms that at the moment the lambda is triggered daily with CloudWatch
see http://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html and http://docs.aws.amazon.com/lambda/latest/dg/tutorial-scheduled-events-schedule-expressions.html

**Comment by jamieu** [comment]
Daily is fine!

**Comment by iteles** [comment]
@SimonLab Can this question now be closed?
